### ISSUE TITLE
ARCHER installation error

### ISSUE THREAD

**Issue by willeaton101** [kuangdai/AxiSEM-3D#4]
Hi Kuangdai,

While following the installation page for ARCHER, an error occurs when trying to build the program using the _make -j8_ command. All code from Section 3.1 and Section 3.3 are copied in as blocks of code to the terminal. 

The cmake output is copied here: 
[build_error_message.txt](https://github.com/kuangdai/AxiSEM-3D/files/5475144/build_error_message.txt)

Best wishes,
Will

**Comment by kuangdai** [comment]
Please  upload  output of cmake

**Comment by kuangdai** [comment]
I confirm that the issue is due to a recent update of Eigen.  

I  raised an issue here:
https://gitlab.com/libeigen/eigen/-/issues/2045

Note that the released stable version 3.3.8 is not sufficient for AxiSEM3D.

For now, please use the attached one. Uncompress  it to dependencies/eigen-master/

[eigen-master.zip](https://github.com/kuangdai/AxiSEM-3D/files/5476700/eigen-master.zip)

**Comment by willeaton101** [comment]
Thanks very much for this. Would you still like a copy of the cmake output for reference?

**Comment by kuangdai** [comment]
No. Thanks.
